/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideCloudUp: typeof import("~icons/lucide/cloud-up")["default"]
  const LucideCloudUpload: typeof import("~icons/lucide/cloud-upload")["default"]
  const LucideUser: typeof import("~icons/lucide/user")["default"]
}
