<template>
  <iframe
    v-if="warned && jwt_token"
    :src="'https://view.officeapps.live.com/op/embed.aspx?src=' + srcUrl"
    class="w-[80%] mx-auto h-[90%]"
    frameborder="0"
  >
    This is an embedded
    <a target="_blank" href="http://office.com">Microsoft Office</a> document,
    powered by
    <a target="_blank" href="http://office.com/webapps">Office Online</a
    >.</iframe
  >
  <div
    v-else
    class="max-w-[450px] px-16 py-8 z-10 bg-white rounded-md text-neutral-100 text-xl text-center font-medium shadow-xl flex flex-col justify-center items-center"
  >
    <LucideAlertCircle class="size-8 mb-6" />
    <span class="mb-4">Are you sure you want to preview?</span>
    <span class="text-base text-center text-gray-700">
      This preview is generated by an external service (<b>Microsoft</b>), not
      by Drive. For extra privacy, we'd suggest downloading.
    </span>
    <Button
      class="mt-4 w-full"
      variant="subtle"
      @click="warned = true"
      :loading="jwt_token === ''"
    >
      View anyway
    </Button>
    <Button class="mt-4 w-full" variant="solid" @click="download">
      Download
    </Button>
  </div>
</template>
<script setup>
import { computed, ref, watch } from "vue"
const props = defineProps({
  previewEntity: Object,
})

const warned = ref(false)
watch(warned, async () => {
  jwt_token.value = ""
  const res = await fetch(
    "/api/method/drive.api.files.create_auth_token?entity_name=" +
      props.previewEntity.name
  )
  const { message } = JSON.parse(await res.text())
  jwt_token.value = message
  console.log(jwt_token.value)
})
const jwt_token = ref(null)
const srcUrl = computed(
  () =>
    new URL(
      `/api/method/drive.api.files.get_file_content?jwt_token=${jwt_token.value}&entity_name=${props.previewEntity.name}&trigger_download=1`,
      window.location.origin
    ).href
)
const download = () => (window.location.ref = srcUrl.value)
</script>
